apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: private-quarkus-devfile-sample-bhju
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: private-quarkus-devfile-sample-bhju
    app.kubernetes.io/part-of: private-devfile
  name: private-quarkus-devfile-sample-bhju
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: private-quarkus-devfile-sample-bhju
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: private-quarkus-devfile-sample-bhju
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-eush-tenant/private-devfile/private-quarkus-devfile-sample-bhju@sha256:4db2dacd4c60f4483d166d85a3bd75551bc32677826a737a65975d7d39d7ce02
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
